idle_bg = "#272822"
idle_fg = "#f8f8f2"
info_bg = "#272822"
info_fg = "#f8f8f2"
good_bg = "#272822"
good_fg = "#75715e"
warning_bg = "#b58900"
warning_fg = "#a1efe4"
critical_bg = "#dc322f"
critical_fg = "#a6e22e"
separator = "\ue0b2"
separator_bg = "#272822"
separator_fg = "#75715e"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
