#!/bin/bash

# Check if there's a default branch name
branch=$(command git rev-parse --abbrev-ref origin/HEAD 2>/dev/null)

if [[ $? == 0 ]]; then
    # This is a git repo

    if [[ -z ${branch} ]]; then
        # If no branch exists, retrieve the new default branch name and try again
        command git remote set-head origin -a
        command git rev-parse --abbrev-ref origin/HEAD 2>/dev/null | cut -c8-
    else
        # Otherwise, strip 'origin/' and echo
        echo ${branch} | cut -c8-
    fi
else
    exit 1
fi
