#!/bin/bash

INPUTS=$(pactl list sink-inputs short | grep -v '-' | awk '{print $1" "$2" "$3}')

COMBINED_OUTPUT=$(pactl list sinks short | grep -i 'combined' | awk '{print $1}')
HEADPHONE_OUTPUT=$(pactl list sinks short | grep -i 'speaker' | awk '{print $1}')

echo "Combined output: $COMBINED_OUTPUT | Headphone output: $HEADPHONE_OUTPUT"
echo "Moving outputs to $1"

if [[ $1 == 'headphones' ]]; then
    OUTPUT=$HEADPHONE_OUTPUT
else
    OUTPUT=$COMBINED_OUTPUT
fi

# Use a while loop to read the INPUTS line by line
# while read -r line; do
while read line; do

    # Split the line into variables using read
    read -r input_id output_id app_id <<< "$line"

    echo "Application $app_id: $input_id -> $OUTPUT"

    pactl move-sink-input $input_id $OUTPUT;

    # Sleep a bit because if you don't the output
    # doesn't always swap. Even with 0.1...
    sleep 0.2

done <<< "$INPUTS"
