#!/bin/bash

TYPE="${BLOCK_INSTANCE:-caps}"

lockLine=$(xset -q | grep "Num Lock")

capsLock=$(echo "${lockLine}" | awk -F ' ' '{print $4}')
numLock=$(echo "${lockLine}" | awk -F ' ' '{print $8}')
scrollLock=$(echo "${lockLine}" | awk -F ' ' '{print $12}')

if [[ "${TYPE}" == "caps" && "${capsLock}" == "on" ]]; then
    echo '<span size="large" weight="bold" background="#DAA520" foreground="#000000">caps lock</span>'
elif [[ "${TYPE}" == "num" && "${numLock}" == "on" ]]; then
    echo '<span size="large" weight="bold" background="#DAA520" foreground="#000000">num lock</span>'
elif [[ "${TYPE}" == "scroll" && "${scrollLock}" == "on" ]]; then
    echo '<span size="large" weight="bold" background="#DAA520" foreground="#000000">scroll lock</span>'
else
  exit
fi
