platforms = ["laptop", "desktop"]

[templates]
".screenlayout/{}_default.sh" = ".screenlayout/default.sh"
".config/i3/{}_config" = ".config/i3/config"
".config/i3/{}_status.toml" = ".config/i3/status.toml"
".config/sway/{}_config" = ".config/sway/config"
".config/sway/{}_status.toml" = ".config/sway/status.toml"
".config/bspwm/{}_bspwmrc" = ".config/bspwm/bspwmrc"
".config/polybar/{}_config.ini" = ".config/polybar/config.ini"
".config/polybar/{}_modules.ini" = ".config/polybar/modules.ini"
".xprofile_{}" = ".xprofile"
".config/waybar/{}_config" = ".config/waybar/config"
