laptop:
    .screenlayout/laptop_default.sh: .screenlayout/default.sh
    .config/i3/laptop_config: .config/i3/config
    .config/i3/laptop_status.toml: .config/i3/status.toml
desktop:
    .screenlayout/desktop_default.sh: .screenlayout/default.sh
    .config/i3/desktop_config: .config/i3/config
    .config/i3/desktop_status.toml: .config/i3/status.toml
