platforms = ["laptop", "desktop"]

[templates]
".screenlayout/{}_default.sh" = ".screenlayout/default.sh"
".config/i3/{}_config" = ".config/i3/config"
".config/i3/{}_status.toml" = ".config/i3/status.toml"
".config/sway/{}_config" = ".config/sway/config"
".config/sway/{}_status.toml" = ".config/sway/status.toml"
".config/kitty/{}_kitty.conf" = ".config/kitty/kitty.conf"
".config/waybar/{}_config" = ".config/waybar/config"
".config/waybar/{}_style.css" = ".config/waybar/style.css"
