laptop, desktop:
    .screenlayout/{}_default.sh: .screenlayout/default.sh
    .config/i3/{}_config: .config/i3/config
    .config/i3/{}_status.toml: .config/i3/status.toml
    .config/bspwm/{}_bspwmrc: .config/bspwm/bspwmrc
