#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         3
bspc config window_gap          10
bspc config top_padding         10

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config normal_border_color  "#444444"
bspc config focused_border_color "#5e81ac"

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pgrep -x picom > /dev/null || picom &
pgrep -x pasystray > /dev/null || pasystray &
feh --bg-fill ~/.config/wallpapers/pebbles_stones_dark_152025_3840x2160.jpg
pgrep -x polybar > /dev/null || polybar -r -c ~/.config/polybar/config.ini main
